# 该工作流将使用Ant构建Java项目
# 更多信息请参见：https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

名字：HiFINI-自动签到

在输入：
  工作流派送：

    - cron: "00 16 * * *"

工作：
  构建：
    环境：
      Cookie：${{ secretsCookie }}
      服务器酱：${{ secrets.SERVER_CHAN }}
      钉钉 webhook：${{ secrets.DINGTALK_WEBHOOK }}{{ secrets.DINGTALK_WEBHOOK }}
      WXWORK_WEBHOOK：${{ secrets.WXWORK_WEBHOOK }}
      TG_CHAT_ID：{{ secrets.TG_CHAT_ID }}
      TG_BOT_TOKEN：${{ secrets.TG_BOT_TOKEN }}
      GOTIFY_URL：${{ secrets.GOTIFY_URL }}
      GOTIFY_APP_TOKEN：${{ secrets.GOTIFY_APP_TOKEN }}
    运行于：ubuntu-latest

    步骤：
      - 用途： actions/checkout@v3
      - 名字： 设置 JDK 8
        用途：actions/setup-java@v3
        与:
          java-version: '8'
          分布：'temurin'
      - 名字: 用Maven构建
        运行: |
          mvn compile
          mvn exec:java -Dexec.mainClass="cloud.ohiyou.Main"
